# Generated by Django 3.1.2 on 2021-03-18 10:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210310_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelas',
            name='geom',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parcelas',
            name='geom_4326',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='parcelas',
            name='num_animales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcelas',
            name='num_balas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
