# Generated by Django 3.1.2 on 2021-03-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelas',
            old_name='percen_alimento_para_vacas',
            new_name='porcen_alimento_para_vacas',
        ),
        migrations.RenameField(
            model_name='parcelas',
            old_name='percen_suelo_desnudo',
            new_name='porcen_suelo_desnudo',
        ),
        migrations.RenameField(
            model_name='parcelas',
            old_name='percen_suelo_desnudo_salida',
            new_name='porcen_suelo_desnudo_salida',
        ),
        migrations.AddField(
            model_name='parcelas',
            name='geom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
